
// src/lib/firebase.ts
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// IMPORTANT: This file is used to configure Firebase.
// This configuration was generated by the AI assistant.
const firebaseConfig = {
  "projectId": "global-stop",
  "appId": "1:902072408470:web:a9b19b24c5e791a84865b7",
  "apiKey": "AIzaSyDw63q5Hn0TCDIFMggy_YV9PQ-fUvmNDJQ",
  "authDomain": "global-stop.firebaseapp.com",
  "measurementId": "G-P41T2BEMKZ",
  "messagingSenderId": "902072408470",
  "storageBucket": "global-stop.appspot.com"
};

// Initialize Firebase App
// This pattern ensures that we don't initialize the app more than once.
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
