// IMPORTANT: This file is used to configure Firebase.
// It is safe to expose this configuration publicly.
// Security is enforced by Firebase Security Rules.

// This configuration was generated by the AI assistant.
// Do not modify this file unless you are certain of the changes.

export const firebaseConfig = {
  "apiKey": "AIzaSyChgL6C45Yq2CQVzmcC4fnSCpWq4h2fE4E",
  "authDomain": "global-stop.firebaseapp.com",
  "projectId": "global-stop",
  "storageBucket": "global-stop.appspot.com",
  "messagingSenderId": "902072408470",
  "appId": "1:902072408470:web:a9b19b24c5e791a84865b7"
};
