// IMPORTANT: This file is used to configure Firebase.
// It is safe to expose this configuration publicly.
// Security is enforced by Firebase Security Rules.

// This configuration was generated by the AI assistant.
// Do not modify this file unless you are certain of the changes.

export const firebaseConfig = {
  "projectId": "global-stop",
  "appId": "1:902072408470:web:a9b19b24c5e791a84865b7",
  "apiKey": "AIzaSyDw63q5Hn0TCDIFMggy_YV9PQ-fUvmNDJQ",
  "authDomain": "global-stop.firebaseapp.com",
  "measurementId": "G-P41T2BEMKZ",
  "messagingSenderId": "902072408470",
  "storageBucket": "global-stop.appspot.com"
};
